### ISSUE TITLE
Jquery Isn't Working

### ISSUE THREAD

**Issue by MJSchell** [AndrewScheller2006/Nextech#1]
JQuery is built into popcode, but not into regular HTML, CSS, JS therefore when run on the popcode website it doesn't need an "import"

You should call jquery before your script tag with `<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>` and move your script tag `<script src="script.js"></script>`  along with the jquery import to before your ending body tag

It should look like the following:
```
<body>
    (divs etc. the body of the website)

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
    <script src="script.js"></script>
</body>
```

**Comment by AndrewScheller2006** [comment]
Ok, thanks mason!


Sent from Yahoo Mail for iPhone


On Wednesday, October 12, 2022, 1:29 PM, M Schel ***@***.***> wrote:




JQuery is built into popcode, but not into regular HTML, CSS, JS therefore when run on the popcode website it doesn't need an "import"

You should call jquery before your script tag with <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script> and move your script tag <script src="script.js"></script> along with the jquery import to before your ending body tag

It should look like the following:
<body>
    (divs etc. the body of the website)

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
    <script src="script.js"></script>
</body>
